version: '3.8'

services:
  # Dịch vụ Cơ sở dữ liệu PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: bookstore-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # Dịch vụ Quản trị Giao diện pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bookstore-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

  # Dịch vụ Cache Redis
  redis:
    image: redis:7-alpine
    container_name: bookstore-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

# Khai báo phân vùng lưu trữ dữ liệu lâu dài
volumes:
  postgres_data:
  redis_data: