spring.application.name=demo

# PostgreSQL config
spring.datasource.url=jdbc:postgresql://localhost:5432/testing
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123123

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Log SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

#JWT key
jwt.signerKey=z8p4p8X9vY2bN5mR7qW1eT4uI0oP3aS6dF9gH2jK5lZ8x