# ==========================================
# DEVELOPMENT ENVIRONMENT PROFILE (dev)
# ==========================================

# PostgreSQL config for Local Development
spring.datasource.url=jdbc:postgresql://localhost:5432/testing
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123123

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

# Show SQL queries in console (Helpful for debugging)
spring.jpa.show-sql=true

# Redis config for Local Development
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Logging Level
logging.level.com.example.bookstore=DEBUG

# Session Cookie Security Configuration
server.servlet.session.cookie.secure=false
