CREATE TABLE IF NOT EXISTS employee (
    employee_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code VARCHAR(20)  NOT NULL,
    full_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(100) NOT NULL,
    role          VARCHAR(50)  NOT NULL,
    department    VARCHAR(50)  NOT NULL,
    role_embedding VARCHAR(1000),
    deleted_at    BIGINT NOT NULL DEFAULT 0,
    UNIQUE (employee_code, deleted_at),
    UNIQUE (email, deleted_at)
);

CREATE TABLE IF NOT EXISTS project (
    project_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code VARCHAR(20)  NOT NULL,
    project_name VARCHAR(200) NOT NULL,
    customer     VARCHAR(100),
    status       VARCHAR(20)  NOT NULL DEFAULT 'PLANNING',
    start_date   DATE,
    end_date     DATE,
    description_embedding VARCHAR(1000),
    deleted_at    BIGINT NOT NULL DEFAULT 0,
    UNIQUE (project_code, deleted_at)
);

CREATE TABLE IF NOT EXISTS skill (
    skill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS employee_skill (
    employee_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    PRIMARY KEY (employee_id, skill_id),
    FOREIGN KEY (employee_id) REFERENCES employee(employee_id) ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES skill(skill_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS allocation (
    allocation_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id        BIGINT       NOT NULL,
    project_id         BIGINT       NOT NULL,
    allocation_percent INT          NOT NULL,
    role_in_project    VARCHAR(100) NOT NULL,
    start_date         DATE         NOT NULL,
    end_date           DATE,
    status             VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    FOREIGN KEY (employee_id) REFERENCES employee(employee_id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES project(project_id) ON DELETE CASCADE
);
