-- 1. Create category table
CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    version INT
);

-- 2. Create books table
CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    category_id BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    version INT,
    CONSTRAINT fk_books_category FOREIGN KEY (category_id) REFERENCES category (id)
);

-- 3. Create app_users table
CREATE TABLE app_users (
    id VARCHAR(255) PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    version INT
);

-- 4. Create role table
CREATE TABLE role (
    name VARCHAR(255) PRIMARY KEY,
    description VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- 5. Create permission table
CREATE TABLE permission (
    name VARCHAR(255) PRIMARY KEY,
    description VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- 6. Create app_users_roles junction table
CREATE TABLE app_users_roles (
    user_id VARCHAR(255) NOT NULL,
    roles_name VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, roles_name),
    CONSTRAINT fk_app_users_roles_user FOREIGN KEY (user_id) REFERENCES app_users (id),
    CONSTRAINT fk_app_users_roles_role FOREIGN KEY (roles_name) REFERENCES role (name)
);

-- 7. Create role_permissions junction table
CREATE TABLE role_permissions (
    role_name VARCHAR(255) NOT NULL,
    permissions_name VARCHAR(255) NOT NULL,
    PRIMARY KEY (role_name, permissions_name),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_name) REFERENCES role (name),
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permissions_name) REFERENCES permission (name)
);

-- 8. Create InvalidatedToken table
CREATE TABLE "InvalidatedToken" (
    id VARCHAR(255) PRIMARY KEY,
    expiry_time TIMESTAMP
);

-- 9. Create app_orders table
CREATE TABLE app_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    total_amount DOUBLE PRECISION NOT NULL,
    status VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_app_orders_user FOREIGN KEY (user_id) REFERENCES app_users (id)
);

-- 10. Create app_order_items table
CREATE TABLE app_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    book_id BIGINT,
    quantity INT NOT NULL,
    price_at_purchase DOUBLE PRECISION NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_app_order_items_order FOREIGN KEY (order_id) REFERENCES app_orders (id),
    CONSTRAINT fk_app_order_items_book FOREIGN KEY (book_id) REFERENCES books (id)
);
